import { useState, useCallback } from "react";
import { YtProject, YtProjectTrack } from "../../hooks/useYtProjects";

export interface AvailableLang {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface VideoDetails {
  title: string | null;
  author: string | null;
  videoId: string;
}

type Step = "auto-video" | "auto-langs" | "auto-fetch" | "done";

interface FetchStatus {
  lang: string;
  label: string;
  state: "waiting" | "fetching" | "done" | "error";
  lines?: number;
  error?: string;
}

function extractVideoId(input: string): string {
  const clean = input.trim();
  const m =
    clean.match(/(?:youtu\.be\/|[?&]v=)([\w-]{11})/) ||
    clean.match(/^([\w-]{11})$/);
  return m ? m[1] : clean;
}

interface Props {
  onClose: () => void;
  onProjectCreated: (project: YtProject) => void;
  prefillVideoId?: string;
  prefillVideoDetails?: VideoDetails | null;
  prefillAvailLangs?: AvailableLang[];
}

export default function NewProjectWizard({
  onClose,
  onProjectCreated,
  prefillVideoId,
  prefillVideoDetails,
  prefillAvailLangs,
}: Props) {
  const [videoInput, setVideoInput]       = useState(prefillVideoId || "");
  const [videoDetails, setVideoDetails]   = useState<VideoDetails | null>(prefillVideoDetails || null);
  const [availLangs, setAvailLangs]       = useState<AvailableLang[]>(prefillAvailLangs || []);
  const [selectedLangs, setSelectedLangs] = useState<Set<string>>(() =>
    prefillAvailLangs?.length ? new Set([prefillAvailLangs[0].languageCode]) : new Set()
  );
  const [fetchStatuses, setFetchStatuses] = useState<FetchStatus[]>([]);
  const [langError,  setLangError]  = useState("");
  const [langLoading, setLangLoading] = useState(false);
  const [builtProject, setBuiltProject] = useState<YtProject | null>(null);

  // Skip to lang selection if we already have the language list from the top-menu lookup
  const [step, setStep] = useState<Step>(
    prefillAvailLangs?.length ? "auto-langs" : "auto-video"
  );

  const autoVideoId = extractVideoId(videoInput);

  // ── Discover available languages ────────────────────────────────────────────
  const handleDiscoverLangs = useCallback(async () => {
    const vid = autoVideoId;
    if (!vid) return;
    setLangError("");
    setLangLoading(true);
    try {
      const r = await fetch(`/api/transcript/languages?videoId=${encodeURIComponent(vid)}`);
      if (!r.ok) {
        const j = await r.json().catch(() => ({ error: r.statusText }));
        throw new Error(j.error || `HTTP ${r.status}`);
      }
      const data = await r.json();
      setVideoDetails({
        title:  data.videoDetails?.title  || null,
        author: data.videoDetails?.author || null,
        videoId: vid,
      });
      const langs: AvailableLang[] = (data.availableLanguages || []).map((l: any) => ({
        languageCode: l.languageCode || l.lang || String(l),
        name: l.name || l.language || l.languageCode || String(l),
        isAutoGenerated: !!l.isAutoGenerated,
      }));
      setAvailLangs(langs);
      if (langs.length) setSelectedLangs(new Set([langs[0].languageCode]));
      setStep("auto-langs");
    } catch (e: any) {
      setLangError(e.message);
    } finally {
      setLangLoading(false);
    }
  }, [autoVideoId]);

  const toggleLang = (code: string) => {
    setSelectedLangs(prev => {
      const next = new Set(prev);
      next.has(code) ? next.delete(code) : next.add(code);
      return next;
    });
  };

  // ── Fetch selected transcripts ───────────────────────────────────────────────
  const handleFetchSelected = useCallback(async () => {
    const vid = prefillVideoId || autoVideoId;
    if (!selectedLangs.size || !vid) return;

    const ordered  = availLangs.filter(l => selectedLangs.has(l.languageCode));
    const statuses: FetchStatus[] = ordered.map(l => ({
      lang: l.languageCode, label: l.name, state: "waiting" as const,
    }));
    setFetchStatuses(statuses);
    setStep("auto-fetch");

    const tracks: YtProjectTrack[] = [];
    for (let i = 0; i < ordered.length; i++) {
      const lang     = ordered[i];
      const langCode = lang.languageCode.split("-")[0];
      setFetchStatuses(prev =>
        prev.map((s, idx) => idx === i ? { ...s, state: "fetching" as const } : s)
      );
      try {
        const r = await fetch(`/api/srt?videoId=${encodeURIComponent(vid)}&lang=${langCode}`);
        if (!r.ok) {
          const j = await r.json().catch(() => ({ error: r.statusText }));
          throw new Error(j.error || `HTTP ${r.status}`);
        }
        const srtContent = await r.text();
        const lineCount  = (srtContent.match(/\n{2,}/g) || []).length + 1;
        tracks.push({ lang: lang.languageCode, langLabel: lang.name, isAutoGenerated: lang.isAutoGenerated, srtContent });
        setFetchStatuses(prev =>
          prev.map((s, idx) => idx === i ? { ...s, state: "done" as const, lines: lineCount } : s)
        );
      } catch (e: any) {
        setFetchStatuses(prev =>
          prev.map((s, idx) => idx === i ? { ...s, state: "error" as const, error: e.message } : s)
        );
      }
    }

    const usedDetails = videoDetails || prefillVideoDetails;
    const project: YtProject = {
      id:        vid,
      videoId:   vid,
      title:     usedDetails?.title  || vid,
      author:    usedDetails?.author || undefined,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      mode:      "auto",
      tracks,
      playOrder: ["video", ...tracks.map(t => `track:${t.lang}`)],
      lastPlayedLine: 0,
    };
    setBuiltProject(project);
    setStep("done");
  }, [availLangs, selectedLangs, autoVideoId, prefillVideoId, videoDetails, prefillVideoDetails]);

  const usedDetails = videoDetails || prefillVideoDetails;

  // ── Shared status list ───────────────────────────────────────────────────────
  const statusList = (
    <div className="yt-wizard-fetch-list">
      {fetchStatuses.map((s, i) => (
        <div key={i} className={`yt-wizard-fetch-item yt-wizard-fetch-${s.state}`}>
          <span className="yt-wizard-fetch-icon">
            {s.state === "waiting" ? "○"
             : s.state === "fetching" ? "⏳"
             : s.state === "done"    ? "✓" : "✕"}
          </span>
          <span className="yt-wizard-fetch-label">{s.label} [{s.lang}]</span>
          {s.state === "done"  && <span className="yt-wizard-fetch-meta">{s.lines} lines</span>}
          {s.state === "error" && <span className="yt-wizard-fetch-err">{s.error}</span>}
        </div>
      ))}
    </div>
  );

  return (
    <div className="yt-wizard-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="yt-wizard-modal">
        <div className="yt-wizard-header">
          <span>New Project</span>
          <button className="yt-wizard-close" onClick={onClose}>✕</button>
        </div>

        {/* Video info banner */}
        {usedDetails?.title && (
          <div className="yt-wizard-video-banner">
            <span className="yt-wizard-video-icon">📺</span>
            <span className="yt-wizard-video-title">{usedDetails.title}</span>
            {usedDetails.author && (
              <span className="yt-wizard-video-author">by {usedDetails.author}</span>
            )}
          </div>
        )}

        {/* ── Step: enter video URL ── */}
        {step === "auto-video" && (
          <div className="yt-wizard-body">
            <label className="yt-wizard-label">YouTube URL or video ID</label>
            <div className="yt-wizard-row">
              <input className="yt-url-input" type="text" value={videoInput}
                onChange={e => setVideoInput(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter") handleDiscoverLangs(); }}
                placeholder="https://www.youtube.com/watch?v=… or video ID"
                autoFocus />
              <button className="yt-load-btn" onClick={handleDiscoverLangs}
                disabled={!autoVideoId || langLoading}>
                {langLoading ? "Discovering…" : "Discover"}
              </button>
            </div>
            {autoVideoId && autoVideoId !== videoInput && (
              <p className="yt-video-id-hint">ID: {autoVideoId}</p>
            )}
            {langError && <div className="yt-error" style={{ marginTop: 8 }}>⚠ {langError}</div>}
          </div>
        )}

        {/* ── Step: language selection ── */}
        {step === "auto-langs" && (
          <div className="yt-wizard-body">
            <p className="yt-wizard-hint">
              {availLangs.length} language{availLangs.length !== 1 ? "s" : ""} available — select which to fetch:
            </p>
            <div className="yt-wizard-lang-list">
              {availLangs.map(l => (
                <label key={l.languageCode}
                  className={`yt-wizard-lang-item${selectedLangs.has(l.languageCode) ? " selected" : ""}`}>
                  <input type="checkbox" checked={selectedLangs.has(l.languageCode)}
                    onChange={() => toggleLang(l.languageCode)} />
                  <span className="yt-wizard-lang-name">{l.name}</span>
                  <span className="yt-wizard-lang-code">[{l.languageCode}]</span>
                  {l.isAutoGenerated && <span className="yt-wizard-auto-badge">auto</span>}
                </label>
              ))}
            </div>
            <div className="yt-wizard-footer">
              {!prefillAvailLangs?.length && (
                <button className="yt-wizard-back" onClick={() => setStep("auto-video")}>← Back</button>
              )}
              <button className="yt-load-btn" onClick={handleFetchSelected}
                disabled={selectedLangs.size === 0}>
                Fetch {selectedLangs.size} transcript{selectedLangs.size !== 1 ? "s" : ""}
              </button>
            </div>
          </div>
        )}

        {/* ── Step: fetching progress ── */}
        {step === "auto-fetch" && (
          <div className="yt-wizard-body">
            <p className="yt-wizard-hint">Fetching transcripts…</p>
            {statusList}
          </div>
        )}

        {/* ── Step: done ── */}
        {step === "done" && (
          <div className="yt-wizard-body">
            <p className="yt-wizard-hint">
              ✓ {fetchStatuses.filter(s => s.state === "done").length} transcript
              {fetchStatuses.filter(s => s.state === "done").length !== 1 ? "s" : ""} ready.
            </p>
            {statusList}
            <div className="yt-wizard-footer">
              <button className="yt-wizard-back" onClick={onClose}>Close</button>
              <button className="yt-load-btn" onClick={() => { if (builtProject) onProjectCreated(builtProject); }}
                disabled={!builtProject}>
                Open Project →
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
