import { YtProject, YtTrack, ProjectConfig } from './types';
import { extractVideoId } from './utils';

export function downloadProject(project: YtProject): void {
  const safeName = (project.title || project.videoId || 'youtube-project')
    .replace(/[\/\\:*?"<>|]+/g, '_')
    .replace(/\s+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 80) || 'youtube-project';
  const blob = new Blob([JSON.stringify(project, null, 2)], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${safeName}.json`;
  link.click();
  URL.revokeObjectURL(url);
}

export function parseProjectFile(text: string): YtProject {
  const value = JSON.parse(text) as Partial<YtProject> & Record<string, any>;
  if (!value || typeof value !== 'object') {
    throw new Error('This file is not a valid YouTube learner project.');
  }

  const videoId = typeof value.videoId === 'string'
    ? (extractVideoId(value.videoId) || value.videoId.trim())
    : extractVideoId(typeof value.videoUrl === 'string' ? value.videoUrl : '');
  const rawTracks = Array.isArray(value.tracks)
    ? value.tracks
    : Array.isArray(value.subtitles) ? value.subtitles
    : Array.isArray(value.transcripts) ? value.transcripts
    : [];
  const tracks: YtTrack[] = rawTracks
    .map((track: any, index: number) => ({
      lang: String(track.lang || track.languageCode || track.language || `track${index + 1}`).trim(),
      label: String(track.label || track.name || track.languageName || track.lang || `Track ${index + 1}`).trim(),
      isAuto: Boolean(track.isAuto ?? track.isAutoGenerated ?? track.autoGenerated),
      srtContent: String(track.srtContent ?? track.srt ?? track.content ?? track.text ?? '').trim(),
    }))
    .filter(track => track.srtContent);

  if (!tracks.length) {
    throw new Error('This project does not contain any readable subtitle tracks.');
  }

  const rawConfig = (value.config || {}) as Partial<ProjectConfig> & Record<string, any>;
  const source = typeof rawConfig.translationSource === 'string' && rawConfig.translationSource.startsWith('track:')
    ? rawConfig.translationSource
    : `track:${tracks[0].lang}`;
  const trackColIds = tracks.map(track => `track:${track.lang}`);
  const colOrder = Array.from(new Set([
    ...trackColIds,
    ...(Array.isArray(rawConfig.colOrder) ? rawConfig.colOrder.filter((id: any) => typeof id === 'string') : []),
  ])).filter(id => id !== 'translation' && id !== 'video');
  colOrder.push('translation');
  if (videoId) colOrder.push('video');

  const rawSettings = rawConfig.colSettings && typeof rawConfig.colSettings === 'object'
    ? rawConfig.colSettings
    : {};
  const colSettings: ProjectConfig['colSettings'] = {};
  tracks.forEach((track, index) => {
    const colId = `track:${track.lang}`;
    colSettings[colId] = {
      visible: rawSettings[colId]?.visible !== false,
      playOrder: Number.isFinite(rawSettings[colId]?.playOrder) ? rawSettings[colId].playOrder : index + 1,
      ttsRate: Number.isFinite(rawSettings[colId]?.ttsRate) ? rawSettings[colId].ttsRate : 1,
      voiceName: rawSettings[colId]?.voiceName,
    };
  });
  colSettings.translation = {
    visible: rawSettings.translation?.visible !== false,
    playOrder: Number.isFinite(rawSettings.translation?.playOrder) ? rawSettings.translation.playOrder : tracks.length + 1,
    ttsRate: Number.isFinite(rawSettings.translation?.ttsRate) ? rawSettings.translation.ttsRate : 0.9,
    voiceName: rawSettings.translation?.voiceName,
  };
  if (videoId) {
    colSettings.video = {
      visible: rawSettings.video?.visible !== false,
      playOrder: Number.isFinite(rawSettings.video?.playOrder) ? rawSettings.video.playOrder : tracks.length + 2,
      ttsRate: Number.isFinite(rawSettings.video?.ttsRate) ? rawSettings.video.ttsRate : 1,
      voiceName: rawSettings.video?.voiceName,
    };
  }
  const importedVisibleLines = rawConfig.visibleLines;
  const visibleLines = typeof importedVisibleLines === 'number' && Number.isFinite(importedVisibleLines) && importedVisibleLines >= 3
    ? importedVisibleLines
    : 30;
  const config: ProjectConfig = {
    ...rawConfig,
    targetLang: String(rawConfig.targetLang || value.targetLang || value.translationLanguage || ''),
    translationTargets: Array.isArray(rawConfig.translationTargets)
      ? rawConfig.translationTargets.filter((lang: any) => typeof lang === 'string' && lang.trim())
      : rawConfig.colOrder?.includes('translation') && String(rawConfig.targetLang || value.targetLang || '').trim()
        ? [String(rawConfig.targetLang || value.targetLang).trim()]
        : [],
    translationSource: tracks.some(track => `track:${track.lang}` === source) ? source : `track:${tracks[0].lang}`,
    colOrder,
    colSettings,
    visibleLines,
  };
  const createId = () => typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
    ? crypto.randomUUID()
    : `imported-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const title = typeof value.title === 'string' && value.title.trim()
    ? value.title.trim()
    : videoId ? `YouTube video ${videoId}` : 'Imported YouTube project';

  return {
    ...value,
    id: createId(),
    videoId: videoId || '',
    title,
    description: typeof value.description === 'string' ? value.description : '',
    tracks,
    config,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    lastLine: typeof value.lastLine === 'number' ? value.lastLine : 0,
  } as YtProject;
}