import React, { useState } from 'react';
import { YtProject, YtTrack, ProjectConfig, AvailableLang } from './types';
import { LANG_OPTIONS, DEFAULT_TTS_RATE, DEFAULT_VISIBLE_LINES } from './constants';
import appConfig from '../../config/appConfig.json';
import { extractVideoId, dedupeAvailLangs } from './utils';
import { transcriptMethodQueryParam } from '../../services/transcriptMethodConfig';

interface Props {
  onProjectReady: (project: YtProject) => void;
  recentProject: YtProject | null;
  hasHistory: boolean;
  onLoadRecent: () => void;
  onClearHistory: () => void;
}

type Step = 'url' | 'langs';

function buildProject(
  id: string,
  videoId: string,
  title: string,
  tracks: YtTrack[],
  targetLang: string
): YtProject {
  const colOrder: string[] = [...tracks.map(t => `track:${t.lang}`), 'translation', 'video'];
  const colSettings: ProjectConfig['colSettings'] = {};
  tracks.forEach((t, i) => {
    colSettings[`track:${t.lang}`] = { visible: true, playOrder: i + 1, ttsRate: DEFAULT_TTS_RATE };
  });
  colSettings['translation'] = { visible: true, playOrder: tracks.length + 1, ttsRate: 0.9 };
  colSettings['video'] = { visible: !!videoId, playOrder: tracks.length + 2, ttsRate: DEFAULT_TTS_RATE };

  const config: ProjectConfig = {
    targetLang,
    translationSource: `track:${tracks[0].lang}`,
    colOrder,
    colSettings,
    visibleLines: DEFAULT_VISIBLE_LINES,
  };

  return { id, videoId, title, createdAt: Date.now(), updatedAt: Date.now(), tracks, config, lastLine: 0 };
}

export default function SetupView({ onProjectReady, recentProject, hasHistory, onLoadRecent, onClearHistory }: Props) {
  const [step, setStep] = useState<Step>('url');

  // ── URL step ──────────────────────────────────────────────────────────────
  const [url, setUrl] = useState(appConfig.youtube.defaultUrl);
  const [findLoading, setFindLoading] = useState(false);
  const [findError, setFindError] = useState('');

  // ── Language selection step ──────────────────────────────────────────────
  const [videoId, setVideoId] = useState('');
  const [videoTitle, setVideoTitle] = useState<string | null>(null);
  const [availLangs, setAvailLangs] = useState<AvailableLang[]>([]);
  const [primaryLang, setPrimaryLang] = useState('');
  const [extraLangs, setExtraLangs] = useState<Set<string>>(new Set());
  const [targetLang, setTargetLang] = useState(appConfig.youtube.defaultTargetLanguage);
  const [fetchLoading, setFetchLoading] = useState(false);
  const [fetchError, setFetchError] = useState('');

  const handleFindLanguages = async () => {
    setFindError('');
    const vid = extractVideoId(url.trim());
    if (!vid) { setFindError('Could not extract a video ID from that URL.'); return; }
    setFindLoading(true);
    try {
      const res = await fetch(`/api/transcript/languages?videoId=${encodeURIComponent(vid)}`);
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error(j.error || `HTTP ${res.status}`);
      }
      const data = await res.json();
      const langs = dedupeAvailLangs<AvailableLang>((data.availableLanguages || []).map((l: any): AvailableLang => ({
        languageCode: l.languageCode || String(l),
        name: l.name || l.languageCode || String(l),
        isAutoGenerated: !!l.isAutoGenerated,
        isDefault: !!l.isDefault,
      })));
      if (!langs.length) throw new Error('No subtitle tracks found for this video.');
      const defaultLang = langs.find(l => l.isAutoGenerated) || langs.find(l => l.isDefault) || langs[0];
      setVideoId(vid);
      setVideoTitle(data.videoDetails?.title || null);
      setAvailLangs(langs);
      setPrimaryLang(defaultLang.languageCode);
      setExtraLangs(new Set());
      setStep('langs');
    } catch (e: any) {
      setFindError(e.message || 'Failed to fetch available languages');
    }
    setFindLoading(false);
  };

  const toggleExtraLang = (code: string) => {
    setExtraLangs(prev => {
      const next = new Set(prev);
      if (next.has(code)) next.delete(code); else next.add(code);
      return next;
    });
  };

  const handleFetchSelected = async () => {
    setFetchError('');
    if (!primaryLang) { setFetchError('Select a transcript language.'); return; }
    if (!targetLang.trim()) { setFetchError('Enter a target language to translate to.'); return; }
    setFetchLoading(true);
    try {
      const codes = [primaryLang, ...Array.from(extraLangs).filter(c => c !== primaryLang)];
      const chosen = codes
        .map(code => availLangs.find(l => l.languageCode === code))
        .filter((l): l is AvailableLang => !!l);
      const tracks: YtTrack[] = [];
      for (const lang of chosen) {
        const langCode = lang.languageCode.split('-')[0];
        const res = await fetch(`/api/srt?videoId=${encodeURIComponent(videoId)}&lang=${langCode}${transcriptMethodQueryParam()}`);
        if (!res.ok) {
          const j = await res.json().catch(() => ({}));
          throw new Error(j.error || `HTTP ${res.status}`);
        }
        const srtContent = await res.text();
        tracks.push({ lang: lang.languageCode, label: lang.name, isAuto: lang.isAutoGenerated, srtContent });
      }
      onProjectReady(buildProject(videoId, videoId, videoTitle || videoId, tracks, targetLang.trim()));
    } catch (e: any) {
      setFetchError(e.message || 'Error fetching subtitles');
    }
    setFetchLoading(false);
  };

  const handleBack = () => {
    setStep('url');
    setFindError('');
    setFetchError('');
  };

  // ── Render: language selection ───────────────────────────────────────────
  if (step === 'langs') {
    return (
      <div className="yl-setup">
        <div className="yl-setup-hero">
          <h1 className="yl-setup-title">🎓 YouTube Language Learner</h1>
          {videoTitle && <p className="yl-setup-subtitle">{videoTitle}</p>}
        </div>

        <div className="yl-setup-form">
          <label className="yl-label">Transcript language</label>
          <select
            className="yl-select"
            value={primaryLang}
            onChange={e => setPrimaryLang(e.target.value)}
          >
            {availLangs.map(l => (
              <option key={l.languageCode} value={l.languageCode}>
                {l.name}{l.isAutoGenerated ? ' (auto)' : ''}{l.isDefault ? ' — default' : ''}
              </option>
            ))}
          </select>

          {availLangs.length > 1 && (
            <details className="yl-extra-langs">
              <summary className="yl-label">+ Add more transcript tracks (optional)</summary>
              <div className="yl-lang-chips">
                {availLangs.filter(l => l.languageCode !== primaryLang).map(l => (
                  <button
                    key={l.languageCode}
                    type="button"
                    className={`yl-lang-chip ${extraLangs.has(l.languageCode) ? 'yl-lang-chip-loaded' : 'yl-lang-chip-add'}`}
                    onClick={() => toggleExtraLang(l.languageCode)}
                  >
                    {extraLangs.has(l.languageCode) ? '✓' : '+'} {l.name}
                    {l.isAutoGenerated && <span className="yl-auto-badge">auto</span>}
                  </button>
                ))}
              </div>
            </details>
          )}

          <label className="yl-label">Translate subtitles to</label>
          <input
            className="yl-input"
            type="text"
            list="yl-lang-suggestions"
            placeholder="en, he, ar…"
            value={targetLang}
            onChange={e => setTargetLang(e.target.value)}
          />
          <datalist id="yl-lang-suggestions">
            {LANG_OPTIONS.map(l => <option key={l.code} value={l.code}>{l.label}</option>)}
          </datalist>

          {fetchError && <p className="yl-error">{fetchError}</p>}

          <div className="yl-setup-actions">
            <button className="yl-btn-secondary" onClick={handleBack} type="button" disabled={fetchLoading}>
              ← Back
            </button>
            <button className="yl-btn-primary yl-btn-full" onClick={handleFetchSelected} disabled={fetchLoading}>
              {fetchLoading ? 'Fetching…' : 'Load Video →'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Render: URL step ──────────────────────────────────────────────────────
  return (
    <div className="yl-setup">
      <div className="yl-setup-hero">
        <h1 className="yl-setup-title">🎓 YouTube Language Learner</h1>
        <p className="yl-setup-subtitle">
          Watch YouTube videos with synchronized multi-language transcripts and TTS playback.
        </p>
      </div>

      {recentProject && (
        <div className="yl-recent-card">
          <div>
            <div className="yl-recent-label">Resume where you left off</div>
            <div className="yl-recent-title">{recentProject.title}</div>
          </div>
          <button className="yl-btn-primary" onClick={onLoadRecent}>Resume →</button>
        </div>
      )}

      {hasHistory && (
        <div className="yl-clear-history">
          <button className="yl-btn-ghost-danger" onClick={() => {
            if (window.confirm('Clear all YouTube history? This cannot be undone.')) onClearHistory();
          }}>
            🗑 Clear history
          </button>
        </div>
      )}

      <div className="yl-setup-form">
        <label className="yl-label">YouTube URL or Video ID</label>
        <input
          className="yl-input"
          type="text"
          placeholder="https://www.youtube.com/watch?v=..."
          value={url}
          onChange={e => setUrl(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleFindLanguages()}
          autoFocus
        />

        {findError && <p className="yl-error">{findError}</p>}

        <button className="yl-btn-primary yl-btn-full" onClick={handleFindLanguages} disabled={findLoading || !url.trim()}>
          {findLoading ? 'Finding subtitle tracks…' : 'Find subtitle tracks →'}
        </button>

      </div>
    </div>
  );
}
