import React, { useState } from 'react';
import { AvailableLang, YtProject, YtTrack, ProjectConfig } from './types';
import { LANG_OPTIONS, DEFAULT_TTS_RATE, DEFAULT_VISIBLE_LINES } from './constants';
import { extractVideoId } from './utils';

interface Props {
  onProjectReady: (project: YtProject) => void;
  recentProject: YtProject | null;
  onLoadRecent: () => void;
}

type Step = 'url' | 'langs' | 'loading';

export default function SetupView({ onProjectReady, recentProject, onLoadRecent }: Props) {
  const [step, setStep] = useState<Step>('url');
  const [url, setUrl] = useState('');
  const [targetLang, setTargetLang] = useState('he');
  const [videoId, setVideoId] = useState('');
  const [videoTitle, setVideoTitle] = useState('');
  const [availLangs, setAvailLangs] = useState<AvailableLang[]>([]);
  const [selectedLangs, setSelectedLangs] = useState<Set<string>>(new Set());
  const [error, setError] = useState('');
  const [loadingMsg, setLoadingMsg] = useState('');

  const handleLoadUrl = async () => {
    setError('');
    const vid = extractVideoId(url.trim());
    if (!vid) { setError('Could not extract video ID from URL.'); return; }
    setVideoId(vid);
    setLoadingMsg('Fetching available transcript languages…');
    setStep('loading');
    try {
      const res = await fetch(`/api/transcript/languages?videoId=${encodeURIComponent(vid)}`);
      if (!res.ok) { const j = await res.json().catch(() => ({})); throw new Error(j.error || `HTTP ${res.status}`); }
      const data = await res.json();
      const langs: AvailableLang[] = (data.availableLanguages || []).map((l: any) => ({
        languageCode: l.languageCode || String(l),
        name: l.name || l.languageCode || String(l),
        isAutoGenerated: !!l.isAutoGenerated,
      }));
      setVideoTitle(data.videoDetails?.title || vid);
      setAvailLangs(langs);
      setSelectedLangs(langs.length ? new Set([langs[0].languageCode]) : new Set());
      setStep('langs');
    } catch (e: any) {
      setError(e.message || 'Error fetching transcript languages');
      setStep('url');
    }
  };

  const toggleLang = (code: string) =>
    setSelectedLangs(prev => { const n = new Set(prev); n.has(code) ? n.delete(code) : n.add(code); return n; });

  const handleStart = async () => {
    if (!selectedLangs.size) { setError('Select at least one language.'); return; }
    setError('');
    setLoadingMsg('Fetching transcripts…');
    setStep('loading');
    try {
      const ordered = availLangs.filter(l => selectedLangs.has(l.languageCode));
      const tracks: YtTrack[] = [];
      for (const l of ordered) {
        const langCode = l.languageCode.split('-')[0];
        const res = await fetch(`/api/srt?videoId=${encodeURIComponent(videoId)}&lang=${langCode}`);
        if (!res.ok) { const j = await res.json().catch(() => ({})); throw new Error(j.error || `HTTP ${res.status}`); }
        tracks.push({ lang: l.languageCode, label: l.name, isAuto: l.isAutoGenerated, srtContent: await res.text() });
      }

      const colOrder: string[] = [...tracks.map(t => `track:${t.lang}`), 'translation', 'video'];
      const colSettings: ProjectConfig['colSettings'] = {};
      tracks.forEach((t, i) => {
        colSettings[`track:${t.lang}`] = { visible: true, playOrder: i + 1, ttsRate: DEFAULT_TTS_RATE };
      });
      colSettings['translation'] = { visible: true, playOrder: tracks.length + 1, ttsRate: 0.9 };
      colSettings['video']       = { visible: true, playOrder: tracks.length + 2, ttsRate: DEFAULT_TTS_RATE };

      const config: ProjectConfig = {
        targetLang,
        translationSource: `track:${tracks[0].lang}`,
        colOrder,
        colSettings,
        visibleLines: DEFAULT_VISIBLE_LINES,
      };

      onProjectReady({
        id: videoId, videoId, title: videoTitle,
        createdAt: Date.now(), updatedAt: Date.now(),
        tracks, config, lastLine: 0,
      });
    } catch (e: any) {
      setError(e.message || 'Error fetching transcripts');
      setStep('langs');
    }
  };

  if (step === 'loading') {
    return <div className="yl-setup"><div className="yl-spinner">⏳ {loadingMsg}</div></div>;
  }

  if (step === 'langs') {
    return (
      <div className="yl-setup">
        <h2 className="yl-setup-title">📺 {videoTitle}</h2>
        <p className="yl-setup-hint">Select the transcript languages to load:</p>
        {availLangs.length === 0
          ? <p className="yl-error">No transcripts available for this video.</p>
          : (
            <div className="yl-lang-list">
              {availLangs.map(l => (
                <label key={l.languageCode} className="yl-lang-item">
                  <input type="checkbox" checked={selectedLangs.has(l.languageCode)} onChange={() => toggleLang(l.languageCode)} />
                  {l.name} {l.isAutoGenerated && <span className="yl-auto-badge">auto</span>}
                </label>
              ))}
            </div>
          )
        }
        {error && <p className="yl-error">{error}</p>}
        <div className="yl-setup-actions">
          <button className="yl-btn-secondary" onClick={() => setStep('url')}>← Back</button>
          <button className="yl-btn-primary" disabled={!selectedLangs.size} onClick={handleStart}>
            Start Learning →
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="yl-setup">
      <div className="yl-setup-hero">
        <h1 className="yl-setup-title">🎓 YouTube Language Learner</h1>
        <p className="yl-setup-subtitle">
          Watch YouTube videos with synchronized multi-language transcripts and TTS playback.
        </p>
      </div>

      {recentProject && (
        <div className="yl-recent-card">
          <div>
            <div className="yl-recent-label">Resume where you left off</div>
            <div className="yl-recent-title">{recentProject.title}</div>
          </div>
          <button className="yl-btn-primary" onClick={onLoadRecent}>Resume →</button>
        </div>
      )}

      <div className="yl-setup-form">
        <label className="yl-label">YouTube URL or Video ID</label>
        <input
          className="yl-input"
          type="text"
          placeholder="https://www.youtube.com/watch?v=..."
          value={url}
          onChange={e => setUrl(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleLoadUrl()}
          autoFocus
        />

        <label className="yl-label">Translate subtitles to</label>
        <select className="yl-select" value={targetLang} onChange={e => setTargetLang(e.target.value)}>
          {LANG_OPTIONS.map(l => <option key={l.code} value={l.code}>{l.label}</option>)}
        </select>

        {error && <p className="yl-error">{error}</p>}

        <button className="yl-btn-primary yl-btn-full" onClick={handleLoadUrl}>
          Load Video →
        </button>
      </div>
    </div>
  );
}
