export interface YtTrack {
  lang: string;
  label: string;
  isAuto: boolean;
  srtContent: string;
}

export interface ColSetting {
  ttsRate: number;
  playOrder: number;
  visible: boolean;
  muted?: boolean;
  voiceName?: string;
}

export interface ProjectConfig {
  targetLang: string;
  /** Translation languages enabled for this project. Empty means no translation. */
  translationTargets?: string[];
  translationSource: string;
  colOrder: string[];
  colSettings: Record<string, ColSetting>;
  visibleLines: number;
}

export interface YtProject {
  id: string;
  videoId: string;
  title: string;
  description?: string;
  createdAt: number;
  updatedAt: number;
  tracks: YtTrack[];
  config: ProjectConfig;
  lastLine: number;
  /** Last video position in seconds, used with lastLine for resume. */
  lastTime?: number;
  /** Subtitle fetcher used for this project. Older projects default to plus. */
  subtitleService?: SubtitleService;
  /** Optional source caption URL used to recreate shared Invidious projects. */
  subtitleUrl?: string;
  /** Optional Invidious-compatible alternate host, e.g. https://yewtu.be. */
  alternateYoutubeUrl?: string;
  /** Optional Webshare/HTTP proxy URL used by the transcript API client. */
  subtitleProxyUrl?: string;
}

export type SubtitleService = 'plus' | 'api-js' | 'onrender' | 'iframe' | 'invidious';

export const SUBTITLE_SERVICE_INFO: Record<SubtitleService, {
  label: string;
  library: string;
  supportsAlternate: boolean;
  supportsProxy: boolean;
}> = {
  plus: {
    label: 'Transcript Plus',
    library: 'youtube-transcript-plus',
    supportsAlternate: false,
    supportsProxy: false,
  },
  'api-js': {
    label: 'Transcript API.js',
    library: 'youtube-transcript-api-js',
    supportsAlternate: true,
    supportsProxy: true,
  },
  onrender: {
    label: 'Hosted captions',
    library: 'youtube-dl-jrte.com',
    supportsAlternate: false,
    supportsProxy: false,
  },
  iframe: {
    label: 'YouTube player',
    library: 'YouTube embedded player',
    supportsAlternate: false,
    supportsProxy: false,
  },
  invidious: {
    label: 'Invidious',
    library: 'Invidious captions API',
    supportsAlternate: false,
    supportsProxy: false,
  },
};

export type YoutubeTheme = 'light' | 'dark' | 'blue';

export interface ParsedLine {
  index: number;
  startSec: number;
  endSec: number;
  texts: Record<string, string>;
  translation: string;
  translated: boolean;
  translations?: Record<string, string>;
  translatedTargets?: Record<string, boolean>;
}

export interface AvailableLang {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isDefault?: boolean;
  subtitleUrl?: string;
}
