export interface YtTrack {
  lang: string;
  label: string;
  isAuto: boolean;
  srtContent: string;
}

export interface ColSetting {
  ttsRate: number;
  playOrder: number;
  visible: boolean;
  voiceName?: string;
}

export interface ProjectConfig {
  targetLang: string;
  translationSource: string;
  colOrder: string[];
  colSettings: Record<string, ColSetting>;
  visibleLines: number;
}

export interface YtProject {
  id: string;
  videoId: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  tracks: YtTrack[];
  config: ProjectConfig;
  lastLine: number;
}

export interface ParsedLine {
  index: number;
  startSec: number;
  endSec: number;
  texts: Record<string, string>;
  translation: string;
  translated: boolean;
}

export interface AvailableLang {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isDefault?: boolean;
}
