export interface YtTrack {
  lang: string;
  label: string;
  isAuto: boolean;
  srtContent: string;
}

export interface ColSetting {
  ttsRate: number;
  playOrder: number;
  visible: boolean;
  voiceName?: string;
}

export interface ProjectConfig {
  targetLang: string;
  translationSource: string;
  colOrder: string[];
  colSettings: Record<string, ColSetting>;
  visibleLines: number;
}

export interface YtProject {
  id: string;
  videoId: string;
  title: string;
  description?: string;
  createdAt: number;
  updatedAt: number;
  tracks: YtTrack[];
  config: ProjectConfig;
  lastLine: number;
  /** Last video position in seconds, used with lastLine for resume. */
  lastTime?: number;
  /** Subtitle fetcher used for this project. Older projects default to plus. */
  subtitleService?: 'plus' | 'api-js' | 'onrender' | 'iframe';
  /** Optional Invidious-compatible alternate host, e.g. https://yewtu.be. */
  alternateYoutubeUrl?: string;
  /** Optional Webshare/HTTP proxy URL used by the transcript API client. */
  subtitleProxyUrl?: string;
}

export type YoutubeTheme = 'light' | 'dark' | 'blue';

export interface ParsedLine {
  index: number;
  startSec: number;
  endSec: number;
  texts: Record<string, string>;
  translation: string;
  translated: boolean;
}

export interface AvailableLang {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isDefault?: boolean;
}
