describe('YouTube learner language and translation settings', () => {
    const project = {
        id: 'language-settings-project',
        videoId: 'lXCAHAJR2-Q',
        title: 'Language settings project',
        description: 'Language settings fixture',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        lastLine: 0,
        tracks: [{
            lang: 'en',
            label: 'English',
            isAuto: false,
            srtContent: '1\n00:00:00,000 --> 00:00:02,000\nHello world.\n\n2\n00:00:02,000 --> 00:00:04,000\nHow are you?',
        }],
        config: {
            targetLang: '',
            translationTargets: [],
            translationSource: 'track:en',
            colOrder: ['track:en', 'video'],
            colSettings: {
                'track:en': { visible: true, playOrder: 1, ttsRate: 1 },
                video: { visible: true, playOrder: 2, ttsRate: 1 },
            },
            visibleLines: 30,
        },
    };

    beforeEach(() => {
        cy.clearLocalStorage();
        cy.intercept('GET', '/api/transcript/languages*', {
            statusCode: 200,
            body: {
                availableLanguages: [
                    { languageCode: 'en', name: 'English', isAutoGenerated: false },
                    { languageCode: 'ar', name: 'Arabic', isAutoGenerated: false },
                ],
            },
        });
        cy.intercept('GET', '/api/srt*', {
            statusCode: 200,
            body: '1\n00:00:00,000 --> 00:00:02,000\nمرحبا بالعالم.\n\n2\n00:00:02,000 --> 00:00:04,000\nكيف حالك؟',
        });
        cy.intercept('GET', 'https://translate.googleapis.com/**', {
            statusCode: 200,
            body: [[['Translated subtitle']]],
        });
    });

    const seedProject = (win: Window) => {
        win.localStorage.setItem('yt-learner-projects', JSON.stringify([project]));
        win.localStorage.setItem('yt-learner-last', project.id);
    };

    const openSettings = () => {
        cy.visit('/youtube/view/language-settings-project', { onBeforeLoad: seedProject });
        cy.contains('button', 'Settings').click();
    };

    it('loads Arabic through Manage languages and renders the added track', () => {
        openSettings();
        cy.contains('button', 'Manage languages').click();
        cy.contains('button', '+ Arabic').click();
        cy.wait(1000);
        cy.contains('.yl-lang-chip-loaded', 'Arabic').should('be.visible');
        cy.get('.yl-table thead th').should('contain.text', 'Arabic');
        cy.get('.yl-table tbody .yl-row').should('have.length', 2);
    });

    it('translates to Arabic, persists translation order, and cancels English translation', () => {
        openSettings();

        cy.get('[aria-label="New translation language"]').type('ar');
        cy.contains('button', 'Add translation').click();
        cy.wait(1000);
        cy.get('.yl-col-card').should('contain.text', 'Arabic');
        cy.get('.yl-table thead th').should('contain.text', 'Arabic');
        cy.contains('.yl-td-text', 'Translated subtitle').should('be.visible');

        cy.get('[aria-label="New translation language"]').type('en');
        cy.contains('button', 'Add translation').click();
        cy.wait(1000);
        cy.get('.yl-col-card').should('contain.text', 'English');

        cy.get('[data-col-id="translation:en"]')
            .find('input[type="number"]')
            .click().type('{selectall}1').blur();
        cy.wait(1000);
        cy.window().then(win => {
            const projects = JSON.parse(win.localStorage.getItem('yt-learner-projects') || '[]');
            const saved = projects.find((item: typeof project) => item.id === project.id);
            expect(saved.config.colSettings['translation:ar'].playOrder).to.equal(2);
            expect(saved.config.colSettings['translation:en'].playOrder).to.equal(1);
        });

        cy.get('[data-col-id="translation:en"]').find('button', { timeout: 10000 }).contains('Remove').click();
        cy.wait(1000);
        cy.get('[data-col-id="translation:en"]').should('not.exist');
        cy.window().then(win => {
            const projects = JSON.parse(win.localStorage.getItem('yt-learner-projects') || '[]');
            const saved = projects.find((item: typeof project) => item.id === project.id);
            expect(saved.config.translationTargets).to.not.include('en');
            expect(saved.config.colOrder).to.not.include('translation:en');
        });
    });
});
