import { useState, useCallback } from "react";

export interface YtProjectTrack {
  lang: string;
  langLabel: string;
  isAutoGenerated: boolean;
  translatedFrom?: string;
  srtContent: string;
}

export interface YtProject {
  id: string;
  videoId: string;
  title: string;
  author?: string;
  createdAt: number;
  updatedAt: number;
  mode: "auto" | "manual";
  tracks: YtProjectTrack[];
  playOrder: string[];
  lastPlayedLine: number;
}

const STORAGE_KEY = "yt-projects";
const LAST_KEY    = "yt-last-project";
const MAX_PROJECTS = 50;

function readAll(): YtProject[] {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); }
  catch { return []; }
}

function writeAll(list: YtProject[]) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(list)); }
  catch (e) { console.warn("useYtProjects: write failed", e); }
}

export function useYtProjects() {
  const [projects, setProjects] = useState<YtProject[]>(readAll);

  const saveProject = useCallback((project: YtProject) => {
    setProjects(prev => {
      const idx = prev.findIndex(p => p.id === project.id);
      const next = idx >= 0
        ? prev.map(p => p.id === project.id ? project : p)
        : [project, ...prev].slice(0, MAX_PROJECTS);
      writeAll(next);
      return next;
    });
  }, []);

  const deleteProject = useCallback((id: string) => {
    setProjects(prev => {
      const next = prev.filter(p => p.id !== id);
      writeAll(next);
      return next;
    });
  }, []);

  const getLastProjectId = useCallback(
    () => localStorage.getItem(LAST_KEY),
    []
  );

  const setLastProjectId = useCallback((id: string) => {
    localStorage.setItem(LAST_KEY, id);
  }, []);

  return { projects, saveProject, deleteProject, getLastProjectId, setLastProjectId };
}
