const express = require("express");
const cors = require("cors");
const swaggerUi = require("swagger-ui-express");

const app = express();

// ── Swagger / OpenAPI spec ─────────────────────────────────────────────────────
const swaggerSpec = {
  openapi: "3.0.0",
  info: {
    title: "YouTube Transcript & TTS API",
    version: "1.0.0",
    description:
      "Server-side proxy for YouTube transcript fetching, language discovery, " +
      "Google TTS, and OpenRouter AI chat. All transcript endpoints correspond to " +
      "the `srt_fetch.js` service design.",
  },
  servers: [{ url: "/", description: "This server (port 3001 proxied)" }],
  tags: [
    { name: "Transcripts", description: "YouTube caption / SRT endpoints" },
    { name: "TTS",         description: "Text-to-speech proxy" },
    { name: "AI",          description: "OpenRouter chat proxy" },
    { name: "Health",      description: "Server status" },
  ],
  paths: {
    "/api/transcript/languages": {
      get: {
        tags: ["Transcripts"],
        summary: "List available caption languages for a video",
        description:
          "Fetches the YouTube player API for the given video and returns all " +
          "available caption tracks with their language code, human-readable name, " +
          "and whether the track is auto-generated (ASR).",
        parameters: [
          {
            name: "videoId",
            in: "query",
            required: true,
            description: "YouTube video ID or full watch URL",
            schema: { type: "string", example: "dQw4w9WgXcQ" },
          },
        ],
        responses: {
          200: {
            description: "Language list and basic video metadata",
            content: {
              "application/json": {
                example: {
                  videoDetails: {
                    title: "Rick Astley - Never Gonna Give You Up",
                    author: "Rick Astley",
                    lengthSeconds: "212",
                    videoId: "dQw4w9WgXcQ",
                  },
                  availableLanguages: [
                    { languageCode: "en", name: "English", isAutoGenerated: true },
                    { languageCode: "fr", name: "French",  isAutoGenerated: false },
                  ],
                },
              },
            },
          },
          400: { description: "Missing videoId" },
          500: { description: "YouTube fetch error" },
        },
      },
    },
    "/api/srt": {
      get: {
        tags: ["Transcripts"],
        summary: "Fetch a transcript as SRT text",
        description:
          "Fetches the transcript for a YouTube video in the requested language " +
          "and returns it as plain-text SRT. Tries `youtube-transcript-plus` first, " +
          "then falls back to the YouTube timedtext API (with `&tlang=` for server-side " +
          "translation), then `youtube-transcript-api-js`.",
        parameters: [
          {
            name: "videoId",
            in: "query",
            required: true,
            description: "YouTube video ID",
            schema: { type: "string", example: "dQw4w9WgXcQ" },
          },
          {
            name: "lang",
            in: "query",
            required: false,
            description: "BCP-47 language code (short form, e.g. `en`, `he`, `ar`). Defaults to `en`.",
            schema: { type: "string", example: "en" },
          },
        ],
        responses: {
          200: {
            description: "SRT-formatted transcript",
            content: {
              "text/plain": {
                example:
                  "1\n00:00:01,000 --> 00:00:04,000\nNever gonna give you up\n\n" +
                  "2\n00:00:04,500 --> 00:00:07,000\nNever gonna let you down",
              },
            },
          },
          400: { description: "Missing videoId" },
          500: { description: "All fetch methods failed" },
        },
      },
    },
    "/api/tts": {
      get: {
        tags: ["TTS"],
        summary: "Google TTS audio proxy",
        description:
          "Proxies a Google Translate TTS request server-side to avoid browser CORS " +
          "and User-Agent blocks. Returns an MP3 audio buffer. Text is truncated to " +
          "200 characters.",
        parameters: [
          {
            name: "text",
            in: "query",
            required: true,
            description: "Text to synthesise (max 200 chars)",
            schema: { type: "string", example: "Hello world" },
          },
          {
            name: "lang",
            in: "query",
            required: true,
            description: "Short language code, e.g. `en`, `he`, `ar`",
            schema: { type: "string", example: "en" },
          },
        ],
        responses: {
          200: {
            description: "MP3 audio data",
            content: { "audio/mpeg": {} },
          },
          400: { description: "Missing text or lang" },
          500: { description: "TTS upstream error" },
        },
      },
    },
    "/api/health": {
      get: {
        tags: ["Health"],
        summary: "Server liveness check",
        responses: {
          200: {
            description: "Server is up",
            content: {
              "application/json": {
                example: { ok: true, uptime: 42, age: "42s" },
              },
            },
          },
        },
      },
    },
    "/api/config": {
      get: {
        tags: ["Health"],
        summary: "Check whether the server has an API key configured",
        responses: {
          200: {
            description: "Key presence flag",
            content: {
              "application/json": {
                example: { serverHasKey: true },
              },
            },
          },
        },
      },
    },
    "/api/chat": {
      post: {
        tags: ["AI"],
        summary: "OpenRouter chat completions proxy",
        description:
          "Forwards a chat request to OpenRouter. Accepts an optional `apiKey` " +
          "override in the body; falls back to the server-side `OPENROUTER_API_KEY`.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              example: {
                model: "meta-llama/llama-3.1-8b-instruct:free",
                messages: [{ role: "user", content: "Hello!" }],
                apiKey: "(optional override)",
              },
            },
          },
        },
        responses: {
          200: { description: "OpenRouter response (streamed or buffered)" },
          401: { description: "No API key" },
          500: { description: "OpenRouter error" },
        },
      },
    },
  },
};
const PORT = process.env.PORT || 3001;
const ENV_KEY =
  process.env.OPENROUTER_API_KEY || process.env.REACT_APP_OPENAI_API_KEY || "";

const SERVER_START = Date.now();

const formatAge = (ms) => {
  const totalSec = Math.floor(ms / 1000);
  const d = Math.floor(totalSec / 86400);
  const h = Math.floor((totalSec % 86400) / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if (d > 0) return `${d}d ${h}h ${m}m ${s}s`;
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
};

// ── middleware ─────────────────────────────────────────────────────────────────
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// ── Swagger UI ────────────────────────────────────────────────────────────────
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
  customSiteTitle: "Transcript API Docs",
  swaggerOptions: { defaultModelsExpandDepth: -1 },
}));
app.get("/api-docs.json", (_req, res) => res.json(swaggerSpec));

// ── structured logger ─────────────────────────────────────────────────────────
const log = (level, msg, meta = {}) => {
  const ts = new Date().toISOString();
  const rest = Object.keys(meta).length ? " " + JSON.stringify(meta) : "";
  console.log(`[${ts}] [${level.toUpperCase()}] ${msg}${rest}`);
};

// ── request logger middleware ─────────────────────────────────────────────────
app.use((req, _res, next) => {
  log("info", `${req.method} ${req.path}`);
  next();
});

// ── middleware: prevent caching on all API routes ──────────────────────────────
app.use("/api", (_req, res, next) => {
  res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
  res.set("Pragma", "no-cache");
  res.set("Expires", "0");
  next();
});

// ── health ────────────────────────────────────────────────────────────────────
app.get("/api/health", (_req, res) => {
  const now = Date.now();
  res.json({
    ok: true,
    timestamp: now,
    startedAt: SERVER_START,
    age: formatAge(now - SERVER_START),
    uptime: Math.floor(process.uptime()),
  });
});

// ── config (lets client know if server has a key) ────────────────────────────
app.get("/api/config", (_req, res) => {
  res.json({ serverHasKey: !!ENV_KEY });
});

// ── health_ai: verify the OpenRouter key actually works ───────────────────────
app.post("/api/health_ai", async (req, res) => {
  const { apiKey } = req.body || {};
  const key = apiKey || ENV_KEY;

  if (!key) {
    return res.status(401).json({
      ok: false,
      error:
        "No API key available. Set OPENROUTER_API_KEY on the server or pass one in the request body.",
    });
  }

  const t0 = Date.now();
  try {
    const orRes = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:5000",
        "X-Title": "Voice Translation App",
      },
      body: JSON.stringify({
        model: "meta-llama/llama-3.1-8b-instruct:free",
        messages: [{ role: "user", content: "Reply with the single word: OK" }],
        max_tokens: 5,
      }),
    });

    const elapsed = Date.now() - t0;

    if (!orRes.ok) {
      const body = await orRes.text().catch(() => "");
      log("warn", "health_ai: OpenRouter rejected key", {
        status: orRes.status,
        elapsed,
      });
      return res.status(200).json({
        ok: false,
        status: orRes.status,
        error: body.slice(0, 200) || orRes.statusText,
        elapsed,
        timestamp: Date.now(),
      });
    }

    const data = await orRes.json();
    const reply = data?.choices?.[0]?.message?.content || "";
    log("info", "health_ai: key OK", { elapsed, reply });
    return res.json({ ok: true, elapsed, reply, timestamp: Date.now() });
  } catch (err) {
    const elapsed = Date.now() - t0;
    log("error", "health_ai: fetch failed", { error: err.message, elapsed });
    return res
      .status(500)
      .json({ ok: false, error: err.message, elapsed, timestamp: Date.now() });
  }
});

// ── free models: proxy OpenRouter model catalogue (avoids browser CORS) ───────
app.get("/api/free-models", async (_req, res) => {
  try {
    const orRes = await fetch(
      "https://openrouter.ai/api/frontend/models/find?active=true&fmt=cards&max_price=0&order=top-weekly",
      { headers: { Accept: "application/json" } },
    );
    if (!orRes.ok) {
      return res
        .status(orRes.status)
        .json({ error: "OpenRouter returned " + orRes.status });
    }
    const data = await orRes.json();
    // Response shape: { data: { models: [...] } }
    const rawList =
      data?.data?.models ?? data?.data ?? data?.models ?? data ?? [];
    const models = rawList
      .map((m) => ({
        id: m.slug || m.id || "",
        label: m.name || m.short_name || m.slug || "",
      }))
      .filter((m) => m.id);
    res.json({ models });
  } catch (err) {
    log("error", "free-models fetch failed", { error: err.message });
    res.status(500).json({ error: err.message });
  }
});

// ── chat proxy ────────────────────────────────────────────────────────────────
app.post("/api/chat", async (req, res) => {
  const { messages, model, apiKey, maxTokens } = req.body || {};

  if (!Array.isArray(messages) || !model) {
    return res
      .status(400)
      .json({ error: "messages (array) and model (string) are required" });
  }

  const key = apiKey || ENV_KEY;
  if (!key) {
    return res.status(401).json({
      error:
        "No API key available. Set OPENROUTER_API_KEY on the server, or enter one in the UI.",
    });
  }

  const keySource = apiKey ? "ui" : "server-env";
  log("info", "OpenRouter request", {
    model,
    messages: messages.length,
    keySource,
    maxTokens,
  });

  const orBody = { model, messages };
  if (maxTokens && Number.isInteger(maxTokens) && maxTokens > 0) {
    orBody.max_tokens = maxTokens;
  }

  const t0 = Date.now();
  try {
    const orRes = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
        "HTTP-Referer":
          req.headers.referer || req.headers.origin || "http://localhost:5000",
        "X-Title": "Voice Translation App",
      },
      body: JSON.stringify(orBody),
    });

    const elapsed = Date.now() - t0;

    if (!orRes.ok) {
      const body = await orRes.text().catch(() => "");
      log("error", "OpenRouter error", {
        status: orRes.status,
        body: body.slice(0, 200),
        elapsed,
      });
      return res.status(orRes.status).json({
        error: `OpenRouter ${orRes.status}: ${body || orRes.statusText}`,
      });
    }

    const data = await orRes.json();
    const content = data?.choices?.[0]?.message?.content;
    const actualModel = data?.model || model;

    if (!content) {
      log("error", "Empty content in OpenRouter response", { data });
      return res
        .status(500)
        .json({ error: "No content in OpenRouter response" });
    }

    const keySuffix = key.length > 4 ? `...${key.slice(-4)}` : key ? "***" : "none";

    log("info", "OpenRouter OK", {
      model,
      actualModel,
      elapsed,
      keySuffix,
      promptTokens: data.usage?.prompt_tokens,
      completionTokens: data.usage?.completion_tokens,
    });

    res.json({ content, model: actualModel, keySuffix });
  } catch (err) {
    const elapsed = Date.now() - t0;
    log("error", "OpenRouter fetch failed", { error: err.message, elapsed });
    res.status(500).json({ error: err.message });
  }
});

// ── SRT helpers ───────────────────────────────────────────────────────────────
const { fetchTranscript } = require("youtube-transcript-plus");

function padN(n, len) { return String(n).padStart(len, "0"); }
function msToSrtTime(ms) {
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  const x = Math.floor(ms % 1000);
  return `${padN(h,2)}:${padN(m,2)}:${padN(s,2)},${padN(x,3)}`;
}
function segmentsToSrt(segments) {
  return segments
    .map((seg, i) => {
      const start = msToSrtTime(Math.round(seg.offset * 1000));
      const end   = msToSrtTime(Math.round((seg.offset + seg.duration) * 1000));
      return `${i + 1}\n${start} --> ${end}\n${seg.text}`;
    })
    .join("\n\n");
}

// ── YouTube timedtext helper ───────────────────────────────────────────────────
// Fetches captionTrack baseUrl from the YouTube player API, then fetches the
// timedtext XML (with optional &tlang= for server-side translation).
// Retries up to `maxRetries` times on HTTP 429 with exponential back-off.
const RE_XML_TRANSCRIPT = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;

function decodeXml(str) {
  return str
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#(\d+);/g, (_, n) => String.fromCharCode(+n));
}

async function fetchTimedText(url, { retries = 3, delayMs = 6000 } = {}) {
  const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36";
  for (let attempt = 0; attempt <= retries; attempt++) {
    const r = await fetch(url, { headers: { "User-Agent": UA } });
    if (r.status === 429) {
      if (attempt === retries) throw new Error("YouTube rate-limited (429) after retries");
      const wait = delayMs * Math.pow(2, attempt);
      log("warn", `SRT 429 rate-limited, retrying in ${wait}ms`, { attempt });
      await new Promise(ok => setTimeout(ok, wait));
      continue;
    }
    if (!r.ok) throw new Error(`YouTube timedtext HTTP ${r.status}`);
    return r.text();
  }
}

// ── shared player API fetcher (used by /api/transcript/languages and /api/srt) ─
async function ytPlayerData(videoId) {
  const watchPage = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: { "User-Agent": "Mozilla/5.0", "Accept-Language": "en-US,en;q=0.9" },
  });
  if (!watchPage.ok) throw new Error(`Watch page HTTP ${watchPage.status}`);
  const html = await watchPage.text();

  const keyMatch = html.match(/"INNERTUBE_API_KEY":"([^"]+)"/) ||
                   html.match(/INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/);
  if (!keyMatch) throw new Error("Could not extract Innertube API key");

  const playerRes = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${keyMatch[1]}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json", "User-Agent": "Mozilla/5.0" },
      body: JSON.stringify({
        context: { client: { clientName: "ANDROID", clientVersion: "20.10.38" } },
        videoId,
      }),
    }
  );
  if (!playerRes.ok) throw new Error(`Player API HTTP ${playerRes.status}`);
  return playerRes.json();
}

async function ytCaptionBaseUrl(videoId) {
  const data   = await ytPlayerData(videoId);
  const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks?.length) throw new Error("No caption tracks found");
  return tracks[0].baseUrl; // caller appends &tlang if needed
}

// ── /api/transcript/languages — list caption tracks + video info ─────────────
app.get("/api/transcript/languages", async (req, res) => {
  const { videoId } = req.query;
  if (!videoId) return res.status(400).json({ error: "videoId is required" });
  try {
    const data   = await ytPlayerData(String(videoId));
    const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    const vd     = data?.videoDetails || {};
    log("info", "transcript/languages OK", { videoId, n: tracks.length });
    res.json({
      videoDetails: {
        title:         vd.title         || null,
        author:        vd.author        || null,
        lengthSeconds: vd.lengthSeconds || null,
        videoId:       vd.videoId       || videoId,
      },
      availableLanguages: tracks.map(t => ({
        languageCode:    t.languageCode,
        name:            t.name?.simpleText || t.languageCode,
        isAutoGenerated: t.kind === "asr",
      })),
    });
  } catch (e) {
    log("error", "transcript/languages failed", { videoId, error: e.message });
    res.status(500).json({ error: e.message });
  }
});

// ── /api/srt — fetch YouTube transcript as SRT text ───────────────────────────
// Query params: videoId (required), lang (optional, default 'en')
// Uses YouTube's native &tlang= parameter for server-side translation.
app.get("/api/srt", async (req, res) => {
  const { videoId, lang } = req.query;
  if (!videoId) return res.status(400).json({ error: "videoId is required" });
  const langCode = String(lang || "en").split("-")[0];

  let method1Error = null;

  // ── Method 1: direct player API + timedtext with &tlang ──────────────────
  try {
    // First try the library (exact lang match — fastest path, no extra HTTP calls)
    try {
      const segments = await fetchTranscript(String(videoId), { lang: langCode });
      log("info", "SRT m1 exact-lang OK", { videoId, lang: langCode, n: segments.length });
      return res.type("text/plain; charset=utf-8").send(segmentsToSrt(segments));
    } catch {
      // exact lang not available — fall through to tlang approach
    }

    // Get the signed captionTrack baseUrl from the player API
    const baseUrl    = await ytCaptionBaseUrl(String(videoId));
    // Strip any &fmt= the player may have included, then add tlang + XML format
    const timedtextUrl = baseUrl.replace(/&fmt=[^&]*/g, "") + `&tlang=${langCode}`;
    log("info", "SRT m1 fetching tlang", { videoId, lang: langCode, url: timedtextUrl.slice(-80) });

    const xml = await fetchTimedText(timedtextUrl);
    const matches = [...xml.matchAll(RE_XML_TRANSCRIPT)];
    if (!matches.length) throw new Error("No segments parsed from timedtext XML");

    const segments = matches.map(m => ({
      text:     decodeXml(m[3]),
      duration: parseFloat(m[2]),
      offset:   parseFloat(m[1]),
      lang:     langCode,
    }));
    log("info", "SRT m1 tlang OK", { videoId, lang: langCode, n: segments.length });
    return res.type("text/plain; charset=utf-8").send(segmentsToSrt(segments));
  } catch (e1) {
    method1Error = e1.message;
    log("warn", "SRT m1 failed → m2", { videoId, lang: langCode, error: e1.message });
  }

  // ── Method 2: youtube-transcript-api-js (ESM fallback) ───────────────────
  try {
    const { YouTubeTranscriptApi, SRTFormatter } = await import("youtube-transcript-api-js");
    const api  = new YouTubeTranscriptApi();
    const list = await api.list(String(videoId));

    let transcript;
    try {
      transcript = list.findTranscript([langCode]);
    } catch {
      transcript = list.findTranscript(["en", "ar", "he", "fr", "es", "de", "ru", "zh", "ja"]);
    }

    if (transcript.languageCode !== langCode && transcript.isTranslatable
        && transcript.translationLanguagesDict?.has(langCode)) {
      transcript = transcript.translate(langCode);
    }

    const fetched = await transcript.fetch();
    const srt     = new SRTFormatter().formatTranscript(fetched);
    log("info", "SRT m2 OK", { videoId, lang: langCode });
    return res.type("text/plain; charset=utf-8").send(srt);
  } catch (e2) {
    log("error", "SRT both methods failed", { videoId, lang: langCode, e1: method1Error, e2: e2.message });
    return res.status(500).json({ error: `Could not fetch transcript. m1: ${method1Error}. m2: ${e2.message}` });
  }
});

// ── /api/tts — server-side Google TTS proxy (avoids browser CORS/UA blocks) ───
// Query params: text (required), lang (required, short code like 'ar', 'he', 'en')
app.get("/api/tts", async (req, res) => {
  const { text, lang } = req.query;
  if (!text || !lang) return res.status(400).json({ error: "text and lang are required" });
  const shortLang  = String(lang).split("-")[0];
  const encoded    = encodeURIComponent(String(text).slice(0, 200));
  const ttsUrl     = `https://translate.google.com/translate_tts?ie=UTF-8&tl=${shortLang}&client=tw-ob&q=${encoded}`;

  try {
    const upstream = await fetch(ttsUrl, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      },
    });
    if (!upstream.ok) {
      log("warn", "TTS upstream error", { status: upstream.status, lang: shortLang });
      return res.status(upstream.status).json({ error: `TTS upstream returned ${upstream.status}` });
    }
    const buf = Buffer.from(await upstream.arrayBuffer());
    log("info", "TTS OK", { lang: shortLang, bytes: buf.length, textLen: String(text).length });
    res.set("Content-Type", "audio/mpeg");
    res.set("Cache-Control", "public, max-age=3600");
    res.send(buf);
  } catch (err) {
    log("error", "TTS fetch failed", { error: err.message, lang: shortLang });
    res.status(500).json({ error: err.message });
  }
});

// ── start ─────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  log("info", `Server listening on port ${PORT}`);
  log(
    "info",
    `API key source: ${ENV_KEY ? "OPENROUTER_API_KEY env var" : "none (UI must provide key)"}`,
  );
});
