// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-chat/Redesign.tsx": () => import("../components/mockups/ai-chat/Redesign.tsx"),
  "./components/mockups/ai-chat-usability/AccessibilityFirst.tsx": () => import("../components/mockups/ai-chat-usability/AccessibilityFirst.tsx"),
  "./components/mockups/ai-chat-usability/AffordanceFirst.tsx": () => import("../components/mockups/ai-chat-usability/AffordanceFirst.tsx"),
  "./components/mockups/ai-chat-usability/HierarchyFirst.tsx": () => import("../components/mockups/ai-chat-usability/HierarchyFirst.tsx")
};
