import { YouTubeTranscriptApi, SRTFormatter } from 'youtube-transcript-api-js';
import express from 'express';

const app = express();
const PORT = process.env.PORT || 3002;

app.use(express.json());

// Helper: convert fetched segments to VTT format
function segmentsToVtt(segments) {
  const lines = ['WEBVTT', ''];
  segments.forEach((seg, i) => {
    const start = formatTime(seg.start / 1000, 'vtt');
    const end   = formatTime((seg.start + seg.duration) / 1000, 'vtt');
    lines.push(`${i + 1}`, `${start} --> ${end}`, seg.text.replace(/\n/g, ' '), '');
  });
  return lines.join('\n').trim();
}

// Helper: convert fetched segments to JSON format
function segmentsToJson(segments) {
  return segments.map(seg => ({
    offset:   seg.start,
    duration: seg.duration,
    text:     seg.text,
  }));
}

function formatTime(seconds, format) {
  const date = new Date(0);
  date.setSeconds(seconds);
  const ms  = Math.floor((seconds % 1) * 1000).toString().padStart(3, '0');
  const hms = date.toISOString().substr(11, 8);
  return format === 'vtt' ? `${hms}.${ms}` : `${hms},${ms}`;
}

// ── 1. List available languages for a video ──────────────────────────────────
app.get('/transcript/languages', async (req, res, next) => {
  const { videoId } = req.query;

  if (!videoId) {
    return res.status(400).json({ error: 'Missing required query parameter: videoId (URL or ID)' });
  }

  try {
    const api  = new YouTubeTranscriptApi();
    const list = await api.list(String(videoId));

    const languages = list.transcripts.map(t => ({
      languageCode:    t.languageCode,
      name:            t.language,
      isAutoGenerated: t.isGenerated,
      isTranslatable:  t.isTranslatable,
    }));

    res.json({ videoId, availableLanguages: languages });
  } catch (error) {
    next(error);
  }
});

// ── 2. Fetch transcript by language and format ───────────────────────────────
app.get('/transcript', async (req, res, next) => {
  const { videoId, lang, format = 'srt' } = req.query;

  if (!videoId) {
    return res.status(400).json({ error: 'Missing required query parameter: videoId (URL or ID)' });
  }

  const allowedFormats = ['json', 'srt', 'vtt'];
  if (!allowedFormats.includes(format.toLowerCase())) {
    return res.status(400).json({ error: `Invalid format. Allowed formats: ${allowedFormats.join(', ')}` });
  }

  try {
    const api        = new YouTubeTranscriptApi();
    const list       = await api.list(String(videoId));
    const langCode   = lang ? String(lang).split('-')[0] : null;

    let transcript;
    if (langCode) {
      try {
        transcript = list.findTranscript([langCode]);
      } catch {
        // Requested language not directly available — try auto-translation
        const fallback = list.findTranscript(['en', 'ar', 'he', 'fr', 'es', 'de', 'ru', 'zh', 'ja']);
        if (fallback.isTranslatable && fallback.translationLanguagesDict?.has(langCode)) {
          transcript = fallback.translate(langCode);
        } else {
          transcript = fallback;
        }
      }
    } else {
      transcript = list.findTranscript(['en', 'ar', 'he', 'fr', 'es', 'de', 'ru', 'zh', 'ja']);
    }

    const fetched = await transcript.fetch();

    switch (format.toLowerCase()) {
      case 'json':
        return res.json(segmentsToJson(fetched.segments ?? fetched));
      case 'vtt':
        res.setHeader('Content-Type', 'text/vtt; charset=utf-8');
        return res.send(segmentsToVtt(fetched.segments ?? fetched));
      default: {
        const srt = new SRTFormatter().formatTranscript(fetched);
        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        return res.send(srt);
      }
    }
  } catch (error) {
    next(error);
  }
});

// ── Error handling middleware ─────────────────────────────────────────────────
app.use((err, _req, res, _next) => {
  const msg = err?.message || 'An unexpected error occurred.';

  if (msg.includes('Could not find') || msg.includes('not available')) {
    return res.status(404).json({ error: 'TranscriptNotAvailable', message: msg });
  }
  if (msg.includes('disabled')) {
    return res.status(403).json({ error: 'TranscriptsDisabled', message: msg });
  }
  if (msg.includes('language')) {
    return res.status(406).json({ error: 'LanguageNotAvailable', message: msg });
  }

  console.error('Unexpected Error:', err);
  res.status(500).json({ error: 'InternalServerError', message: msg });
});

app.listen(PORT, () => {
  console.log(`YouTube Transcript service (youtube-transcript-api-js) running on http://localhost:${PORT}`);
});
